### PR TITLE
Setup ASP.NET Identity Core 

### PR DESCRIPTION
**Pull request by munteanumarco**
Add the packages for ASP.NET Identity Core 
Modify our context to extend Identity Context
Add Admin and User Role
User Model is the default Identity User as it has enough details for our use case

### CODE REVIEW

**Comment by HellHound97** [comment]
How did you test identity?

**Comment by munteanumarco** [comment]
@HellHound97 I added a new migration, applied it to the database and saw that the identity related tables were created successfully.

**Comment by HellHound97** [comment]
Test the entire flow: create account and login

**Comment by munteanumarco** [comment]
It's just the setup for identity, so we can start and work async.
There are other tasks for the login & register functionality

**Review by gheorghe-sava — APPROVED** [review]

**Review by alexandratodea — APPROVED** [review]

**Pull request merged**
